sudo: required
services:
 - docker

before-install:
 - docker build -t manjirac1988/docker-learn -f Dockerfile.dev .

script:
 - docker run -e CI=true manjirac1988/docker-learn npm run test 

deploy:
 provider: elasticbeanstalk
 region: "us-east-1"
 app: "docker-react"
 env: "Dockerreact-env"
 bucket_name: "elasticbeanstalk-us-east-1-787526580600"
 bucket_path: "docker-react"
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key:
  secure: "$AWS_SECRET_KEY"
